#!/usr/bin/env bash
#
# snort-check.sh ROOT_DIR RULES_FILE — Check 4: RULES_FILE loads under the Snort
# in an unpacked firewall root (from extract-firewall-root.sh). Run as root.
#
# What it does, and why each step is the way it is:
#
#  1. Applies the firewall's own Snort UCI settings. On a real box
#     /etc/uci-defaults/99-rasputin runs at first boot and switches snort-mgr from
#     the package's "manual" mode to the generated config Rasputin ships (tap
#     interface, HOME_NET, alert-only, rasputin-extra.lua). An unpacked image has
#     not booted, so we apply the `set snort.*` lines from THAT image's copy of
#     the file, which always matches the image being tested.
#
#  2. Validates with `snort-mgr -v check`, never bare `snort -T`:
#     - `snort -c /etc/snort/snort.lua -R <rules> -T` fails with thousands of
#       undefined-variable errors, because the variables Rasputin's config needs
#       are generated by snort-mgr, not defined in the stock snort.lua.
#     - `snort-mgr check` WITHOUT -v skips the rules entirely and passes even
#       with a broken rule in place. Only `-v` loads /etc/snort/rules/*.rules.
#
#  3. Runs the check twice: once with an EMPTY community rules file (the
#     baseline: rules the image loads from elsewhere, e.g. file_magic.rules) and
#     once with RULES_FILE. It then requires
#         loaded(candidate) - loaded(baseline) == active rules in RULES_FILE
#     A zero exit code only proves Snort did not reject anything it read; this
#     proves it actually read every rule we are about to publish.
#
# Exits 0 only when Snort validated the configuration and loaded every rule.
# Writes a short report to $SNORT_CHECK_REPORT when that variable is set.
#
# Needs: a Linux host, root (for chroot and mounts).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/lib.sh
. "$SCRIPT_DIR/lib.sh"

[ "$#" -eq 2 ] || die "usage: $0 ROOT_DIR RULES_FILE"
root="$1"
rules="$2"

[ "$(id -u)" -eq 0 ] || die "must run as root (chroot and mounts)"
[ -d "$root" ] || die "no such root directory: $root"
[ -f "$rules" ] || die "no such rules file: $rules"
for path in usr/bin/snort usr/bin/snort-mgr sbin/uci etc/uci-defaults/99-rasputin etc/snort/rules proc dev tmp; do
	[ -e "$root/$path" ] || die "$root has no /$path; is it an unpacked firewall rootfs?"
done

target="$root/etc/snort/rules/snort3-community.rules"
logs="$(mktemp -d)"

mounted=()
cleanup() {
	local i
	for ((i = ${#mounted[@]} - 1; i >= 0; i--)); do
		umount -- "${mounted[$i]}" || echo "WARNING: could not unmount ${mounted[$i]}" >&2
	done
	rm -rf -- "$logs"
}
trap cleanup EXIT

mount_into() {
	# mount_into MOUNTPOINT MOUNT-ARGS...
	local point="$1"
	shift
	mount "$@" "$point" || die "could not mount $point"
	mounted+=("$point")
}

# --- 1. UCI settings from the image's own 99-rasputin -----------------------

uci_lines="$(grep -E '^set snort\.' -- "$root/etc/uci-defaults/99-rasputin" || true)"
[ -n "$uci_lines" ] || die "no 'set snort.' lines in the image's /etc/uci-defaults/99-rasputin; its Snort setup changed and this check must be updated"
# Only plain `set snort.<section>.<option>='<value>'` lines are replayed (the
# value may not contain a quote or a backslash), so nothing else from the file
# can reach the uci batch interpreter.
q="'"
uci_line_re="^set snort\\.[a-z0-9_]+\\.[a-z0-9_]+=${q}[^${q}\\]*${q}\$"
while IFS= read -r line; do
	[[ "$line" =~ $uci_line_re ]] ||
		die "unexpected Snort UCI line in 99-rasputin, refusing to replay it: $line"
done <<<"$uci_lines"
printf '%s\ncommit snort\n' "$uci_lines" >"$logs/uci-batch"

mount_into "$root/proc" -t proc proc
mount_into "$root/dev" --bind /dev
mount_into "$root/tmp" -t tmpfs tmpfs

chroot "$root" /sbin/uci -q batch <"$logs/uci-batch" || die "uci batch failed inside the firewall root"
echo "applied $(wc -l <<<"$uci_lines" | tr -d ' ') Snort UCI settings from the image's 99-rasputin" >&2

snort_version="$(chroot "$root" /usr/bin/snort -V 2>&1 | sed -n 's/.*Version \([0-9][0-9.]*\).*/\1/p' | head -n 1)"
[ -n "$snort_version" ] || die "could not read the Snort version from the firewall root"
echo "Snort in the firewall root: $snort_version" >&2

# run_check NAME — install nothing; run snort-mgr -v check on whatever is at
# $target, keep the log, print "exit_code loaded_count".
run_check() {
	local name="$1" rc=0 loaded
	chroot "$root" /usr/bin/snort-mgr -v check >"$logs/$name.log" 2>&1 || rc=$?
	loaded="$(sed -n 's/^[[:space:]]*total rules loaded:[[:space:]]*\([0-9][0-9]*\)[[:space:]]*$/\1/p' "$logs/$name.log" | head -n 1)"
	printf '%s %s\n' "$rc" "${loaded:-none}"
}

# show_errors NAME — print Snort's ERROR/FATAL lines from a run's log.
show_errors() {
	local log="$logs/$1.log"
	echo "---- Snort ERROR/FATAL lines ($1) ----" >&2
	grep -E '^(ERROR|FATAL|Fatal)' -- "$log" | head -n 50 >&2 || tail -n 40 -- "$log" >&2
	echo "----" >&2
}

# --- 2. Baseline: empty community rules file ---------------------------------

: >"$target"
read -r base_rc base_loaded < <(run_check baseline)
if [ "$base_rc" -ne 0 ] || [ "$base_loaded" = "none" ]; then
	show_errors baseline
	die "the firewall root failed snort-mgr -v check with NO community rules (exit $base_rc); the harness is broken, not the rules"
fi

# --- 3. Candidate --------------------------------------------------------------

install -m 0644 -- "$rules" "$target"
expected="$(count_active_rules "$target")"
read -r cand_rc cand_loaded < <(run_check candidate)

if [ "$cand_rc" -ne 0 ]; then
	show_errors candidate
	die "check 4 FAILED: snort-mgr -v check rejected $rules (exit $cand_rc)"
fi
grep -qF 'Loading /etc/snort/rules/snort3-community.rules' -- "$logs/candidate.log" ||
	die "check 4 FAILED: Snort exited 0 but never loaded /etc/snort/rules/snort3-community.rules"
grep -qF 'Snort successfully validated the configuration' -- "$logs/candidate.log" ||
	die "check 4 FAILED: Snort exited 0 but did not report a validated configuration"
[ "$cand_loaded" != "none" ] || die "check 4 FAILED: could not read 'total rules loaded' from Snort's output"

delta=$((cand_loaded - base_loaded))
if [ "$delta" -ne "$expected" ]; then
	die "check 4 FAILED: Snort loaded $delta rules from $rules but the file has $expected active rules"
fi

echo "check 4 passed: Snort $snort_version validated the configuration and loaded all $expected rules ($cand_loaded total, $base_loaded from the image itself)" >&2

if [ -n "${SNORT_CHECK_REPORT:-}" ]; then
	{
		echo "snort_version=$snort_version"
		echo "rules_loaded=$delta"
		echo "baseline_rules=$base_loaded"
	} >"$SNORT_CHECK_REPORT"
fi
